<?php 
if ($admin != 1) die("go away");

$query = "DROP TABLE IF EXISTS `bios`";
mysql_query($query); 
$check = mysql_error();

$query = "CREATE TABLE `bios` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `display` tinyint(4) DEFAULT '0',
  `featured` tinyint(4) DEFAULT '0',
  `firstname` varchar(255) DEFAULT '',
  `lastname` varchar(255) DEFAULT '',
  `degree` varchar(255) DEFAULT '',
  `field` varchar(255) DEFAULT '',
  `university` varchar(255) DEFAULT '',
  `hometown` varchar(255) DEFAULT '',
  `homecountry` varchar(255) DEFAULT '',
  `homecountry_id` int(4) DEFAULT '0',
  `job` varchar(255) DEFAULT '',
  `workplace` varchar(255) DEFAULT '',
  `minibio` varchar(120) DEFAULT '',
  `google` varchar(255) DEFAULT '',
  `twitter` varchar(255) DEFAULT '',
  `facebook` varchar(255) DEFAULT '',
  `website` varchar(255) DEFAULT '',
  `statement` blob,
  `picture` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`) 
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;	";
mysql_query($query); 
$check = mysql_error();
echo mysql_error();

// Dump of table country
// ------------------------------------------------------------

$query = "DROP TABLE IF EXISTS `country`;";
mysql_query($query); 
$check .= mysql_error();
echo mysql_error();

$query = "CREATE TABLE `country` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `iso` char(2) NOT NULL,
  `name` varchar(80) NOT NULL,
  `printable_name` varchar(80) NOT NULL,
  `iso3` char(3) DEFAULT NULL,
  `numcode` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;	";
mysql_query($query); 
$check .= mysql_error();

$query = "LOCK TABLES `country` WRITE;";
mysql_query($query); 
$check .= mysql_error();

$query = "INSERT INTO `country` (`id`, `iso`, `name`, `printable_name`, `iso3`, `numcode`)
VALUES
	(1,'AD','ANDORRA','Andorra','AND',20),
	(2,'AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE',784),
	(3,'AF','AFGHANISTAN','Afghanistan','AFG',4),
	(4,'AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG',28),
	(5,'AI','ANGUILLA','Anguilla','AIA',660),
	(6,'AL','ALBANIA','Albania','ALB',8),
	(7,'AM','ARMENIA','Armenia','ARM',51),
	(8,'AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT',530),
	(9,'AO','ANGOLA','Angola','AGO',24),
	(10,'AQ','ANTARCTICA','Antarctica',NULL,NULL),
	(11,'AR','ARGENTINA','Argentina','ARG',32),
	(12,'AS','AMERICAN SAMOA','American Samoa','ASM',16),
	(13,'AT','AUSTRIA','Austria','AUT',40),
	(14,'AU','AUSTRALIA','Australia','AUS',36),
	(15,'AW','ARUBA','Aruba','ABW',533),
	(16,'AZ','AZERBAIJAN','Azerbaijan','AZE',31),
	(17,'BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH',70),
	(18,'BB','BARBADOS','Barbados','BRB',52),
	(19,'BD','BANGLADESH','Bangladesh','BGD',50),
	(20,'BE','BELGIUM','Belgium','BEL',56),
	(21,'BF','BURKINA FASO','Burkina Faso','BFA',854),
	(22,'BG','BULGARIA','Bulgaria','BGR',100),
	(23,'BH','BAHRAIN','Bahrain','BHR',48),
	(24,'BI','BURUNDI','Burundi','BDI',108),
	(25,'BJ','BENIN','Benin','BEN',204),
	(26,'BM','BERMUDA','Bermuda','BMU',60),
	(27,'BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN',96),
	(28,'BO','BOLIVIA','Bolivia','BOL',68),
	(29,'BR','BRAZIL','Brazil','BRA',76),
	(30,'BS','BAHAMAS','Bahamas','BHS',44),
	(31,'BT','BHUTAN','Bhutan','BTN',64),
	(32,'BV','BOUVET ISLAND','Bouvet Island',NULL,NULL),
	(33,'BW','BOTSWANA','Botswana','BWA',72),
	(34,'BY','BELARUS','Belarus','BLR',112),
	(35,'BZ','BELIZE','Belize','BLZ',84),
	(36,'CA','CANADA','Canada','CAN',124),
	(37,'CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL),
	(38,'CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD',180),
	(39,'CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF',140),
	(40,'CG','CONGO','Congo','COG',178),
	(41,'CH','SWITZERLAND','Switzerland','CHE',756),
	(42,'CI','COTE D\'IVOIRE','Cote D\'Ivoire','CIV',384),
	(43,'CK','COOK ISLANDS','Cook Islands','COK',184),
	(44,'CL','CHILE','Chile','CHL',152),
	(45,'CM','CAMEROON','Cameroon','CMR',120),
	(46,'CN','CHINA','China','CHN',156),
	(47,'CO','COLOMBIA','Colombia','COL',170),
	(48,'CR','COSTA RICA','Costa Rica','CRI',188),
	(49,'CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL),
	(50,'CU','CUBA','Cuba','CUB',192),
	(51,'CV','CAPE VERDE','Cape Verde','CPV',132),
	(52,'CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL),
	(53,'CY','CYPRUS','Cyprus','CYP',196),
	(54,'CZ','CZECH REPUBLIC','Czech Republic','CZE',203),
	(55,'DE','GERMANY','Germany','DEU',276),
	(56,'DJ','DJIBOUTI','Djibouti','DJI',262),
	(57,'DK','DENMARK','Denmark','DNK',208),
	(58,'DM','DOMINICA','Dominica','DMA',212),
	(59,'DO','DOMINICAN REPUBLIC','Dominican Republic','DOM',214),
	(60,'DZ','ALGERIA','Algeria','DZA',12),
	(61,'EC','ECUADOR','Ecuador','ECU',218),
	(62,'EE','ESTONIA','Estonia','EST',233),
	(63,'EG','EGYPT','Egypt','EGY',818),
	(64,'EH','WESTERN SAHARA','Western Sahara','ESH',732),
	(65,'ER','ERITREA','Eritrea','ERI',232),
	(66,'ES','SPAIN','Spain','ESP',724),
	(67,'ET','ETHIOPIA','Ethiopia','ETH',231),
	(68,'FI','FINLAND','Finland','FIN',246),
	(69,'FJ','FIJI','Fiji','FJI',242),
	(70,'FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK',238),
	(71,'FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM',583),
	(72,'FO','FAROE ISLANDS','Faroe Islands','FRO',234),
	(73,'FR','FRANCE','France','FRA',250),
	(74,'GA','GABON','Gabon','GAB',266),
	(75,'GB','UNITED KINGDOM','United Kingdom','GBR',826),
	(76,'GD','GRENADA','Grenada','GRD',308),
	(77,'GE','GEORGIA','Georgia','GEO',268),
	(78,'GF','FRENCH GUIANA','French Guiana','GUF',254),
	(79,'GH','GHANA','Ghana','GHA',288),
	(80,'GI','GIBRALTAR','Gibraltar','GIB',292),
	(81,'GL','GREENLAND','Greenland','GRL',304),
	(82,'GM','GAMBIA','Gambia','GMB',270),
	(83,'GN','GUINEA','Guinea','GIN',324),
	(84,'GP','GUADELOUPE','Guadeloupe','GLP',312),
	(85,'GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ',226),
	(86,'GR','GREECE','Greece','GRC',300),
	(87,'GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia & the S. Sandwich Islands',NULL,NULL),
	(88,'GT','GUATEMALA','Guatemala','GTM',320),
	(89,'GU','GUAM','Guam','GUM',316),
	(90,'GW','GUINEA-BISSAU','Guinea-Bissau','GNB',624),
	(91,'GY','GUYANA','Guyana','GUY',328),
	(92,'HK','HONG KONG','Hong Kong','HKG',344),
	(93,'HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL),
	(94,'HN','HONDURAS','Honduras','HND',340),
	(95,'HR','CROATIA','Croatia','HRV',191),
	(96,'HT','HAITI','Haiti','HTI',332),
	(97,'HU','HUNGARY','Hungary','HUN',348),
	(98,'ID','INDONESIA','Indonesia','IDN',360),
	(99,'IE','IRELAND','Ireland','IRL',372),
	(100,'IL','ISRAEL','Israel','ISR',376),
	(101,'IN','INDIA','India','IND',356),
	(102,'IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL),
	(103,'IQ','IRAQ','Iraq','IRQ',368),
	(104,'IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN',364),
	(105,'IS','ICELAND','Iceland','ISL',352),
	(106,'IT','ITALY','Italy','ITA',380),
	(107,'JM','JAMAICA','Jamaica','JAM',388),
	(108,'JO','JORDAN','Jordan','JOR',400),
	(109,'JP','JAPAN','Japan','JPN',392),
	(110,'KE','KENYA','Kenya','KEN',404),
	(111,'KG','KYRGYZSTAN','Kyrgyzstan','KGZ',417),
	(112,'KH','CAMBODIA','Cambodia','KHM',116),
	(113,'KI','KIRIBATI','Kiribati','KIR',296),
	(114,'KM','COMOROS','Comoros','COM',174),
	(115,'KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA',659),
	(116,'KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','Korea, Democratic People\'s Republic of','PRK',408),
	(117,'KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR',410),
	(118,'KW','KUWAIT','Kuwait','KWT',414),
	(119,'KY','CAYMAN ISLANDS','Cayman Islands','CYM',136),
	(120,'KZ','KAZAKHSTAN','Kazakhstan','KAZ',398),
	(121,'LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC','Lao People\'s Democratic Republic','LAO',418),
	(122,'LB','LEBANON','Lebanon','LBN',422),
	(123,'LC','SAINT LUCIA','Saint Lucia','LCA',662),
	(124,'LI','LIECHTENSTEIN','Liechtenstein','LIE',438),
	(125,'LK','SRI LANKA','Sri Lanka','LKA',144),
	(126,'LR','LIBERIA','Liberia','LBR',430),
	(127,'LS','LESOTHO','Lesotho','LSO',426),
	(128,'LT','LITHUANIA','Lithuania','LTU',440),
	(129,'LU','LUXEMBOURG','Luxembourg','LUX',442),
	(130,'LV','LATVIA','Latvia','LVA',428),
	(131,'LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY',434),
	(132,'MA','MOROCCO','Morocco','MAR',504),
	(133,'MC','MONACO','Monaco','MCO',492),
	(134,'MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA',498),
	(135,'MG','MADAGASCAR','Madagascar','MDG',450),
	(136,'MH','MARSHALL ISLANDS','Marshall Islands','MHL',584),
	(137,'MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia','MKD',807),
	(138,'ML','MALI','Mali','MLI',466),
	(139,'MM','MYANMAR','Myanmar','MMR',104),
	(140,'MN','MONGOLIA','Mongolia','MNG',496),
	(141,'MO','MACAO','Macao','MAC',446),
	(142,'MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP',580),
	(143,'MQ','MARTINIQUE','Martinique','MTQ',474),
	(144,'MR','MAURITANIA','Mauritania','MRT',478),
	(145,'MS','MONTSERRAT','Montserrat','MSR',500),
	(146,'MT','MALTA','Malta','MLT',470),
	(147,'MU','MAURITIUS','Mauritius','MUS',480),
	(148,'MV','MALDIVES','Maldives','MDV',462),
	(149,'MW','MALAWI','Malawi','MWI',454),
	(150,'MX','MEXICO','Mexico','MEX',484),
	(151,'MY','MALAYSIA','Malaysia','MYS',458),
	(152,'MZ','MOZAMBIQUE','Mozambique','MOZ',508),
	(153,'NA','NAMIBIA','Namibia','NAM',516),
	(154,'NC','NEW CALEDONIA','New Caledonia','NCL',540),
	(155,'NE','NIGER','Niger','NER',562),
	(156,'NF','NORFOLK ISLAND','Norfolk Island','NFK',574),
	(157,'NG','NIGERIA','Nigeria','NGA',566),
	(158,'NI','NICARAGUA','Nicaragua','NIC',558),
	(159,'NL','NETHERLANDS','Netherlands','NLD',528),
	(160,'NO','NORWAY','Norway','NOR',578),
	(161,'NP','NEPAL','Nepal','NPL',524),
	(162,'NR','NAURU','Nauru','NRU',520),
	(163,'NU','NIUE','Niue','NIU',570),
	(164,'NZ','NEW ZEALAND','New Zealand','NZL',554),
	(165,'OM','OMAN','Oman','OMN',512),
	(166,'PA','PANAMA','Panama','PAN',591),
	(167,'PE','PERU','Peru','PER',604),
	(168,'PF','FRENCH POLYNESIA','French Polynesia','PYF',258),
	(169,'PG','PAPUA NEW GUINEA','Papua New Guinea','PNG',598),
	(170,'PH','PHILIPPINES','Philippines','PHL',608),
	(171,'PK','PAKISTAN','Pakistan','PAK',586),
	(172,'PL','POLAND','Poland','POL',616),
	(173,'PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM',666),
	(174,'PN','PITCAIRN','Pitcairn','PCN',612),
	(175,'PR','PUERTO RICO','Puerto Rico','PRI',630),
	(176,'PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL),
	(177,'PT','PORTUGAL','Portugal','PRT',620),
	(178,'PW','PALAU','Palau','PLW',585),
	(179,'PY','PARAGUAY','Paraguay','PRY',600),
	(180,'QA','QATAR','Qatar','QAT',634),
	(181,'RE','REUNION','Reunion','REU',638),
	(182,'RO','ROMANIA','Romania','ROM',642),
	(183,'RU','RUSSIAN FEDERATION','Russian Federation','RUS',643),
	(184,'RW','RWANDA','Rwanda','RWA',646),
	(185,'SA','SAUDI ARABIA','Saudi Arabia','SAU',682),
	(186,'SB','SOLOMON ISLANDS','Solomon Islands','SLB',90),
	(187,'SC','SEYCHELLES','Seychelles','SYC',690),
	(188,'SD','SUDAN','Sudan','SDN',736),
	(189,'SE','SWEDEN','Sweden','SWE',752),
	(190,'SG','SINGAPORE','Singapore','SGP',702),
	(191,'SH','SAINT HELENA','Saint Helena','SHN',654),
	(192,'SI','SLOVENIA','Slovenia','SVN',705),
	(193,'SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM',744),
	(194,'SK','SLOVAKIA','Slovakia','SVK',703),
	(195,'SL','SIERRA LEONE','Sierra Leone','SLE',694),
	(196,'SM','SAN MARINO','San Marino','SMR',674),
	(197,'SN','SENEGAL','Senegal','SEN',686),
	(198,'SO','SOMALIA','Somalia','SOM',706),
	(199,'SR','SURINAME','Suriname','SUR',740),
	(200,'ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP',678),
	(201,'SV','EL SALVADOR','El Salvador','SLV',222),
	(202,'SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR',760),
	(203,'SZ','SWAZILAND','Swaziland','SWZ',748),
	(204,'TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA',796),
	(205,'TD','CHAD','Chad','TCD',148),
	(206,'TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL),
	(207,'TG','TOGO','Togo','TGO',768),
	(208,'TH','THAILAND','Thailand','THA',764),
	(209,'TJ','TAJIKISTAN','Tajikistan','TJK',762),
	(210,'TK','TOKELAU','Tokelau','TKL',772),
	(211,'TL','TIMOR-LESTE','Timor-Leste',NULL,NULL),
	(212,'TM','TURKMENISTAN','Turkmenistan','TKM',795),
	(213,'TN','TUNISIA','Tunisia','TUN',788),
	(214,'TO','TONGA','Tonga','TON',776),
	(215,'TR','TURKEY','Turkey','TUR',792),
	(216,'TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO',780),
	(217,'TV','TUVALU','Tuvalu','TUV',798),
	(218,'TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN',158),
	(219,'TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA',834),
	(220,'UA','UKRAINE','Ukraine','UKR',804),
	(221,'UG','UGANDA','Uganda','UGA',800),
	(222,'UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL),
	(223,'US','UNITED STATES','United States','USA',840),
	(224,'UY','URUGUAY','Uruguay','URY',858),
	(225,'UZ','UZBEKISTAN','Uzbekistan','UZB',860),
	(226,'VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT',336),
	(227,'VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT',670),
	(228,'VE','VENEZUELA','Venezuela','VEN',862),
	(229,'VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB',92),
	(230,'VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR',850),
	(231,'VN','VIET NAM','Viet Nam','VNM',704),
	(232,'VU','VANUATU','Vanuatu','VUT',548),
	(233,'WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF',876),
	(234,'WS','SAMOA','Samoa','WSM',882),
	(235,'YE','YEMEN','Yemen','YEM',887),
	(236,'YT','MAYOTTE','Mayotte',NULL,NULL),
	(237,'ZA','SOUTH AFRICA','South Africa','ZAF',710),
	(238,'ZM','ZAMBIA','Zambia','ZMB',894),
	(239,'ZW','ZIMBABWE','Zimbabwe','ZWE',716);";
mysql_query($query); 
$check .= mysql_error();


$query = "UNLOCK TABLES;";
mysql_query($query); 
$check .= mysql_error();


// Dump of table degree
// ------------------------------------------------------------

$query = "DROP TABLE IF EXISTS `degree`;";
mysql_query($query); 
$check .= mysql_error();


$query = "CREATE TABLE `degree` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `abbrev` varchar(10) DEFAULT '',
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
mysql_query($query); 
$check .= mysql_error();

$query = "LOCK TABLES `degree` WRITE;";
mysql_query($query); 
$check .= mysql_error();

$query = "INSERT INTO `degree` (`id`, `abbrev`, `name`)
VALUES
	(1,'AA','Associate of Arts'),
	(2,'AAS','Associate of Applied Science'),
	(3,'AS','Associate of Science'),
	(4,'BA','Bachelor of Arts'),
	(5,'BAAS','Bachelor of Applied Arts and Science'),
	(6,'BArch','Bachelor of Architecture'),
	(7,'BASc','Bachelor of Applied Science'),
	(8,'BATD','Bachelor of Arts Theater & Dance'),
	(9,'BBA','Bachelor of Business Administration'),
	(10,'BBS','Bachelor of Business Science'),
	(11,'BComm','Bachelor of Commerce'),
	(12,'BD','Bachelor of Divinity'),
	(13,'BEd','Bachelor of Education'),
	(14,'BEng','Bachelor of Engineering'),
	(15,'BFA','Bachelor of Fine Arts'),
	(16,'BIArch','Bachelor of Interior Architecture'),
	(17,'BLA','Bachelor of Landscape Architecture'),
	(18,'BM','Bachelor of Music'),
	(19,'BS','Bachelor of Science'),
	(20,'BST','Bachelor of Sacred Theology'),
	(21,'BSW','Bachelor of Social Work'),
	(22,'CA','Chartered Accountant'),
	(23,'CE','Civil Engineer'),
	(24,'ChE','Chemical Engineer'),
	(25,'CP','Certificate of Proficiency'),
	(26,'CPA','Certified Public Accountant'),
	(27,'CRC','Ceritified Rehabilitation Counselor'),
	(28,'CVE','Certified Vocational Evaluator'),
	(29,'DCL','Doctor of Civil Law'),
	(30,'DDS','Doctor of Dental Surgery'),
	(31,'DEd','Doctor of Education'),
	(32,'DO','Doctor of Osteopathy'),
	(33,'DMA','Doctor of Musical Arts'),
	(34,'DS','Doctor of Science'),
	(35,'DVM','Doctor of Veterinary Medicine'),
	(36,'EBMA','Executive Master of Business Administration'),
	(37,'EdD','Doctor of Education'),
	(38,'EE','Electrical Engineer'),
	(39,'GED','Graduate Equivalency Diploma'),
	(40,'JD','Doctor of Jurisprudence'),
	(41,'LHD','Doctor of Humanities'),
	(42,'LLB','Bachelor of Legal Letters'),
	(43,'LLD','Doctor of Laws'),
	(44,'LPC','Licensed Professional Counselor'),
	(45,'LSW','Licensed Social Worker'),
	(46,'LSWA','Licensed Social Work Associate'),
	(47,'LLB','Bachelor of Laws'),
	(48,'MA','Master of Arts'),
	(49,'MActg','Master of Accounting'),
	(50,'MArch','Master of Architecture'),
	(51,'MAT','Master of Arts in Teaching'),
	(52,'MBA','Master of Business Administration'),
	(53,'MCC','Master of Christian Counseling'),
	(54,'MCE','Master of Civil Engineering'),
	(55,'MCRP','Master of Community & Regional Planning'),
	(56,'MD','Medical Doctor'),
	(57,'ME','Mechanical Engineer'),
	(58,'MEd','Master of Education'),
	(59,'MFA','Master of Fine Arts'),
	(60,'MJ','Master of Journalism'),
	(61,'MHRIR','Master of Human Resources & Industrial Relations'),
	(62,'MIArch','Master of Interior Architecture'),
	(63,'MLA','Master of Landscape Architecture'),
	(64,'MLS','Master of Liberal Studies'),
	(65,'MM','Master of Music'),
	(66,'MMEd','Master of Music Education'),
	(67,'MPA','Master of Public Administration'),
	(68,'MPH','Master of Public Health'),
	(69,'MS','Master of Science'),
	(70,'MSE','Master of Software Engineering'),
	(71,'MSEd','Master of Science Education'),
	(72,'MSW','Master of Social Work'),
	(73,'MTPW','Master of Technical and Professional Writing'),
	(74,'PharmD','Doctor of Pharmacy'),
	(75,'PhB','Bachelor of Philosophy'),
	(76,'PhD','Doctor of Philosophy'),
	(77,'PhG','Graduate in Pharmacy'),
	(78,'RN','Registered Nurse'),
	(79,'VS','Veterinary Surgeon'),
	(80,'HS','High School'),
	(81,'none','none');";
	mysql_query($query); 
	$check .= mysql_error();

$query = "UNLOCK TABLES;";
	mysql_query($query); 
	$check .= mysql_error();

?>